### ISSUE TITLE
mvn package -  fails.

### ISSUE THREAD

**Issue by wwright2** [ImmobilienScout24/yum-repo-client#18]
I think the POM is missing a dependency on apache.commons.io.FileUtils.

mvn -Plocal-dev com.github.joelittlejohn.embedmongo:embedmongo-maven-plugin:start org.codehaus.cargo:cargo-maven2-plugin:run

[devops@devops1 ~/dev/yum-repo-server]$ mvn -Plocal-dev com.github.joelittlejohn.embedmongo:embedmongo-maven-plugin:start org.codehaus.cargo:cargo-maven2-plugin:run
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Yum Repo Server 2.0
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- embedmongo-maven-plugin:0.1.8:start (default-cli) @ yum-repo-server ---
Extract /home/devops/.embedmongo/linux/mongodb-linux-x86_64-2.2.1.tgz START
Extract /home/devops/.embedmongo/linux/mongodb-linux-x86_64-2.2.1.tgz DONE
[INFO]
[INFO] --- cargo-maven2-plugin:1.4.2:run (default-cli) @ yum-repo-server ---
[INFO] [en2.ContainerRunMojo] Resolved container artifact org.codehaus.cargo:cargo-core-container-tomcat:jar:1.4.2 for container tomcat7x
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.737 s
[INFO] Finished at: 2016-11-16T14:24:40-06:00
[INFO] Final Memory: 12M/40M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.cargo:cargo-maven2-plugin:1.4.2:run (default-cli) on project yum-repo-server: Execution default-cli of goal org.codehaus.cargo:cargo-maven2-plugin:1.4.2:run failed: Failed to create deployable with implementation class org.codehaus.cargo.container.tomcat.TomcatWAR for the parameters (container [id = [tomcat7x]], deployable type [war]). InvocationTargetException: Failed to parse Tomcat WAR file in [/home/devops/dev/yum-repo-server/target/yum-repo-server.war]: Failed to find file [/home/devops/dev/yum-repo-server/target/yum-repo-server.war]: /home/devops/dev/yum-repo-server/target/yum-repo-server.war (No such file or directory) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
Exception in thread "Thread-1" java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
        at de.flapdoodle.embed.process.io.file.Files.forceDelete(Files.java:104)
        at de.flapdoodle.embed.process.store.ArtifactStore.removeExecutable(ArtifactStore.java:72)
        at de.flapdoodle.embed.process.store.CachingArtifactStore$FileWithCounter.forceDelete(CachingArtifactStore.java:149)
        at de.flapdoodle.embed.process.store.CachingArtifactStore.removeAll(CachingArtifactStore.java:92)
        at de.flapdoodle.embed.process.store.CachingArtifactStore$CacheCleaner.run(CachingArtifactStore.java:169)
        at java.lang.Thread.run(java.base@9-internal/Thread.java:804)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 6 more

**Comment by mriehl** [comment]
This looks like a yum-repo-server issue, but this is the yum-repo-client repository. Please move the issue to the correct repository.

On-topic: looks like an issue with the embedmongo maven plugin. The caller should depend on fileutils, and the caller is the plugin. Will try to have a look today.

**Comment by mriehl** [comment]
Works like a charm for me (even after throwing away my mvn repository and downloading everything from maven central again, using exactly the command you reported (`mvn -Plocal-dev com.github.joelittlejohn.embedmongo:embedmongo-maven-plugin:start org.codehaus.cargo:cargo-maven2-plugin:run`). Please try to rerun after throwing away `~/.m2/repository`?
